(in-package #:cl-py)

(defun %json-error (message &rest args)
  (error 'adapter-error :message (apply #'format nil message args)))

(defun %json-whitespace-p (character)
  (find character '(#\Space #\Tab #\Newline #\Return) :test #'char=))

(defun %skip-json-whitespace (text index)
  (loop while (and (< index (length text))
                   (%json-whitespace-p (char text index)))
        do (incf index)
        finally (return index)))

(defun %parse-json-string (text index)
  (let ((cursor (1+ index))
        (stream (make-string-output-stream)))
    (loop
      (when (>= cursor (length text))
        (%json-error "Unterminated JSON string"))
      (let ((character (char text cursor)))
        (cond
          ((char= character #\")
           (return (values (get-output-stream-string stream) (1+ cursor))))
          ((char= character #\\)
           (incf cursor)
           (when (>= cursor (length text))
             (%json-error "Unterminated JSON escape sequence"))
           (let ((escape (char text cursor)))
             (case escape
               (#\" (write-char #\" stream))
               (#\\ (write-char #\\ stream))
               (#\/ (write-char #\/ stream))
               (#\b (write-char #\Backspace stream))
               (#\f (write-char #\Page stream))
               (#\n (write-char #\Newline stream))
               (#\r (write-char #\Return stream))
               (#\t (write-char #\Tab stream))
               (#\u
                (when (> (+ cursor 4) (1- (length text)))
                  (%json-error "Incomplete JSON unicode escape"))
                (let* ((hex-start (1+ cursor))
                       (hex-end (+ cursor 5))
                       (hex (subseq text hex-start hex-end))
                       (code (ignore-errors (parse-integer hex :radix 16))))
                  (unless code
                    (%json-error "Invalid JSON unicode escape: ~A" hex))
                  (write-char (or (code-char code)
                                  (%json-error "Unsupported JSON unicode code point: ~A" hex))
                              stream)
                  (setf cursor (+ cursor 4))))
               (otherwise
                (%json-error "Unsupported JSON escape sequence: \\~A" escape)))))
          (t
           (write-char character stream))))
      (incf cursor))))

(defun %parse-json-literal (text index literal value)
  (let ((end (+ index (length literal))))
    (if (and (<= end (length text))
             (string= literal text :start1 0 :end1 (length literal) :start2 index :end2 end))
        (values value end)
        (%json-error "Invalid JSON token near index ~D" index))))

(defun %parse-json-number (text index)
  (let ((cursor index))
    (labels ((current-char ()
               (when (< cursor (length text))
                 (char text cursor)))
             (advance-while (predicate)
               (loop while (and (< cursor (length text))
                                (funcall predicate (char text cursor)))
                     do (incf cursor))))
      (when (char= (current-char) #\-)
        (incf cursor))
      (cond
        ((and (< cursor (length text))
              (char= (char text cursor) #\0))
         (incf cursor))
        ((and (< cursor (length text))
              (digit-char-p (char text cursor)))
         (advance-while #'digit-char-p))
        (t
         (%json-error "Invalid JSON number near index ~D" index)))
      (when (and (< cursor (length text))
                 (char= (char text cursor) #\.))
        (incf cursor)
        (unless (and (< cursor (length text))
                     (digit-char-p (char text cursor)))
          (%json-error "Invalid JSON fractional number near index ~D" index))
        (advance-while #'digit-char-p))
      (when (and (< cursor (length text))
                 (find (char text cursor) "eE" :test #'char=))
        (incf cursor)
        (when (and (< cursor (length text))
                   (find (char text cursor) "+-" :test #'char=))
          (incf cursor))
        (unless (and (< cursor (length text))
                     (digit-char-p (char text cursor)))
          (%json-error "Invalid JSON exponent near index ~D" index))
        (advance-while #'digit-char-p))
      (let* ((token (subseq text index cursor))
             (value (ignore-errors (read-from-string token))))
        (unless value
          (%json-error "Unable to parse JSON number: ~A" token))
        (values value cursor)))))

(defun %parse-json-array (text index)
  (let ((cursor (%skip-json-whitespace text (1+ index)))
        (items nil))
    (if (and (< cursor (length text))
             (char= (char text cursor) #\]))
        (values #() (1+ cursor))
        (loop
          (multiple-value-bind (value next-index) (%parse-json-value text cursor)
            (push value items)
            (setf cursor (%skip-json-whitespace text next-index)))
          (when (>= cursor (length text))
            (%json-error "Unterminated JSON array"))
          (let ((character (char text cursor)))
            (cond
              ((char= character #\,)
               (setf cursor (%skip-json-whitespace text (1+ cursor))))
              ((char= character #\])
               (return (values (coerce (nreverse items) 'vector) (1+ cursor))))
              (t
               (%json-error "Expected ',' or ']' in JSON array at index ~D" cursor))))))))

(defun %parse-json-object (text index)
  (let ((cursor (%skip-json-whitespace text (1+ index)))
        (entries nil))
    (if (and (< cursor (length text))
             (char= (char text cursor) #\}))
        (values (list :object) (1+ cursor))
        (loop
          (unless (and (< cursor (length text))
                       (char= (char text cursor) #\"))
            (%json-error "Expected string key in JSON object at index ~D" cursor))
          (multiple-value-bind (key key-end) (%parse-json-string text cursor)
            (setf cursor (%skip-json-whitespace text key-end))
            (unless (and (< cursor (length text))
                         (char= (char text cursor) #\:))
              (%json-error "Expected ':' after JSON object key at index ~D" cursor))
            (setf cursor (%skip-json-whitespace text (1+ cursor)))
            (multiple-value-bind (value value-end) (%parse-json-value text cursor)
              (push (cons key value) entries)
              (setf cursor (%skip-json-whitespace text value-end))))
          (when (>= cursor (length text))
            (%json-error "Unterminated JSON object"))
          (let ((character (char text cursor)))
            (cond
              ((char= character #\,)
               (setf cursor (%skip-json-whitespace text (1+ cursor))))
              ((char= character #\})
               (return (values (cons :object (nreverse entries)) (1+ cursor))))
              (t
               (%json-error "Expected ',' or '}' in JSON object at index ~D" cursor))))))))

(defun %parse-json-value (text index)
  (let ((cursor (%skip-json-whitespace text index)))
    (when (>= cursor (length text))
      (%json-error "Unexpected end of JSON input"))
    (case (char text cursor)
      (#\{ (%parse-json-object text cursor))
      (#\[ (%parse-json-array text cursor))
      (#\" (%parse-json-string text cursor))
      (#\t (%parse-json-literal text cursor "true" :true))
      (#\f (%parse-json-literal text cursor "false" :false))
      (#\n (%parse-json-literal text cursor "null" :null))
      (otherwise (%parse-json-number text cursor)))))

(defun parse-json (text)
  (multiple-value-bind (value end-index) (%parse-json-value text 0)
    (let ((cursor (%skip-json-whitespace text end-index)))
      (when (< cursor (length text))
        (%json-error "Unexpected trailing JSON content at index ~D" cursor))
      value)))

(defun %json-object-key-string (key)
  (typecase key
    (string key)
    (symbol (string-downcase (symbol-name key)))
    (t (%json-error "JSON object key must be a string or symbol, got ~S" key))))

(defun %json-escape-string (text)
  (with-output-to-string (stream)
    (loop for character across text
          do (case character
               (#\" (write-string "\\\"" stream))
               (#\\ (write-string "\\\\" stream))
               (#\Backspace (write-string "\\b" stream))
               (#\Page (write-string "\\f" stream))
               (#\Newline (write-string "\\n" stream))
               (#\Return (write-string "\\r" stream))
               (#\Tab (write-string "\\t" stream))
               (otherwise
                (if (< (char-code character) 32)
                    (format stream "\\u~4,'0X" (char-code character))
                    (write-char character stream)))))))

(defun %plist-p (value)
  (and (listp value)
       (evenp (length value))
   (loop for rest on value by #'cddr
     for key = (first rest)
     always (or (stringp key) (symbolp key)))))

(defun %parsed-json-object-p (value)
  (and (consp value)
   (eq (car value) :object)
   (loop for entry in (cdr value)
     always (and (consp entry)
         (stringp (car entry))))))

(defun %alist-p (value)
  (and (listp value)
       (loop for entry in value
             always (and (consp entry)
                         (or (stringp (car entry))
                             (symbolp (car entry)))))))

(defun %object-entries (value)
  (cond
    ((%parsed-json-object-p value)
     (values (copy-list (cdr value)) t))
    ((hash-table-p value)
     (let ((entries nil))
       (maphash (lambda (key entry-value)
                  (push (cons (%json-object-key-string key) entry-value) entries))
                value)
       (values entries t)))
    ((%alist-p value)
     (values (mapcar (lambda (entry)
                       (cons (%json-object-key-string (car entry)) (cdr entry)))
                     value)
             t))
    ((%plist-p value)
     (values (loop for rest on value by #'cddr
                   for key = (first rest)
                   for entry-value = (second rest)
                   collect (cons (%json-object-key-string key) entry-value))
             t))
    (t (values nil nil))))

(defun %emit-json-object (entries)
  (format nil
          "{~{~A~^,~}}"
          (mapcar (lambda (entry)
                    (format nil
                            "\"~A\":~A"
                            (%json-escape-string (car entry))
                            (%emit-json-value (cdr entry))))
                  (sort (copy-list entries) #'string< :key #'car))))

(defun %emit-json-array (items)
  (format nil "[~{~A~^,~}]" (map 'list #'%emit-json-value items)))

(defun %emit-json-value (value)
  (multiple-value-bind (object-entries object-p) (%object-entries value)
    (cond
      (object-p
       (%emit-json-object object-entries))
      ((stringp value)
       (format nil "\"~A\"" (%json-escape-string value)))
      ((eq value :true)
       "true")
      ((eq value :false)
       "false")
      ((eq value :null)
       "null")
      ((eq value t)
       "true")
      ((null value)
       "null")
      ((vectorp value)
       (%emit-json-array value))
      ((listp value)
       (%emit-json-array value))
      ((numberp value)
       (princ-to-string value))
      (t
       (%json-error "Unsupported value for JSON emission: ~S" value)))))

(defun emit-json (value)
  (%emit-json-value value))

(defun normalize-json (text)
  (emit-json (parse-json text)))

(defun %read-lisp-json-form (text)
  (let ((*read-eval* nil))
    (multiple-value-bind (value position)
        (read-from-string text)
      (let ((remainder (string-trim '(#\Space #\Tab #\Newline #\Return)
                                    (subseq text position))))
        (unless (string= remainder "")
          (%json-error "Unexpected trailing Lisp input while reading JSON form"))
        value))))

(defun %read-stream-contents (stream)
  (with-output-to-string (output)
    (loop for line = (read-line stream nil nil)
          while line
          do (write-string line output)
             (terpri output))))

(defun %resolve-json-cli-input (text)
  (cond
    ((string= text "-")
     (string-right-trim '(#\Newline #\Return) (%read-stream-contents *standard-input*)))
    ((and (plusp (length text))
          (char= (char text 0) #\@))
     (uiop:read-file-string (subseq text 1)))
    (t
     text)))

(defun %json-cli-parse (text)
  (prin1 (parse-json (%resolve-json-cli-input text)))
  (terpri))

(defun %json-cli-emit (text)
  (format t "~A~%" (emit-json (%read-lisp-json-form (%resolve-json-cli-input text)))))

(defun %json-cli-normalize (text)
  (format t "~A~%" (normalize-json (%resolve-json-cli-input text))))

(defun %print-json-usage ()
  (format t "  json parse <json|@path|->~%")
  (format t "  json emit <lisp-value|@path|->~%")
  (format t "  json normalize <json|@path|->~%"))

(defun dispatch-json-command (args)
  (cond
    ((null args)
     (%print-json-usage))
    ((string= (first args) "parse")
     (if (< (length (rest args)) 1)
         (%print-json-usage)
         (%json-cli-parse (second args))))
    ((string= (first args) "emit")
     (if (< (length (rest args)) 1)
         (%print-json-usage)
         (%json-cli-emit (second args))))
    ((string= (first args) "normalize")
     (if (< (length (rest args)) 1)
         (%print-json-usage)
         (%json-cli-normalize (second args))))
    (t
     (%print-json-usage))))