(defpackage #:cl-py
  (:use #:cl)
  (:export
   #:adapter-error
   #:adapter-not-found
    #:cli-usage-error
   #:python-execution-error
   #:adapter-id
    #:adapter-manifest-version
   #:adapter-name
    #:adapter-upstream-url
    #:adapter-license
   #:adapter-python-module
     #:adapter-python-distribution
    #:adapter-python-requirement
   #:adapter-capabilities
   #:list-adapters
   #:find-adapter
   #:adapter-metadata
   #:adapter-module-version
   #:parse-json
   #:emit-json
   #:normalize-json
   #:parse-iso-timestamp
   #:format-iso-timestamp
   #:normalize-uri
   #:fetch-text
   #:fetch-json
   #:save-registry-snapshot
   #:list-registry-snapshots
  #:inventory-registry-snapshots
   #:load-registry-snapshot
  #:delete-registry-snapshot
  #:delete-registry-snapshots
  #:prune-registry-snapshots
   #:latest-registry-snapshot-id
   #:summarize-registry-snapshot
   #:diff-registry-snapshots
   #:registry-adapter-history
   #:adapter-version-trend
   #:report-registry-snapshot
   #:diff-registry-snapshot-reports
   #:run-bounded-task-batch
   #:normalize-packaging-version
    #:parse-dateutil-isodatetime
    #:slugify-text
   #:validate-jsonschema-instance
   #:parse-yaml
   #:emit-yaml
   #:normalize-yaml
   ;; HTML generation DSL
   #:with-html-output
   #:html-string
   #:html-file
   #:report-registry-to-html
   #:main))

(defpackage #:cl-py.internal
  (:use #:cl)
  (:import-from #:uiop
                #:command-line-arguments
                #:getenv
                #:run-program)
  (:export
   #:*adapter-registry*
   #:adapter
   #:adapter-id
        #:adapter-manifest-version
   #:adapter-name
        #:adapter-upstream-url
        #:adapter-license
   #:adapter-python-module
     #:adapter-python-distribution
        #:adapter-python-requirement
   #:adapter-capabilities
   #:adapter-summary
   #:register-adapter
        #:load-adapter-manifests
  #:register-top-level-cli-command
     #:register-cli-command
  #:dispatch-top-level-command
     #:dispatch-adapter-command
   #:call-python-lines
   #:find-adapter-or-die
  #:help-flag-p
   #:print-cli-usage
  #:print-command-help
  #:signal-cli-usage-error
   #:string-join
   ;; CLI utility exports
   #:parse-non-negative-integer
   #:validate-sort-mode
   #:validate-inventory-sort-mode
   #:parse-keep-count
   #:parse-flag
   #:parse-option
   #:parse-repeatable-option
   #:parse-required-option
   ;; Internal CLI parsing helpers (used by store.lisp)
   #:%parse-flag
   #:%parse-option
   #:%parse-repeatable-option
   #:%parse-required-option
   #:%parse-all-options))
